[package]
name = "rendog-launcher"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[[bin]]
name = "RendogLauncher"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
base64 = "0.22"
log = "0.4"
p256 = { version = "0.13", features = ["ecdsa"] }
png = "0.17"
rand_core = { version = "0.6", features = ["getrandom"] }
reqwest = { version = "0.12", features = ["blocking", "json", "rustls-tls"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"
sha2 = "0.10"
slint = "1.8"

[build-dependencies]
slint-build = "1.8"
winresource = "0.1.31"

[profile.release]
lto = true
codegen-units = 1
strip = true
