[package]
name = "erkuia-launcher-installer"
version = "0.1.1"
edition = "2021"
build = "build.rs"

[[bin]]
name = "Erkuia-Launcher-Installer"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"], default-features = false }
rfd = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
slint = "1.8"

[build-dependencies]
slint-build = "1.8"
winresource = "0.1.31"

[profile.release]
lto = true
codegen-units = 1
strip = true
